---
title: "README"
author: "Roberto Salas"
date: "16/1/2018"
output:
  md_document:
    variant: gfm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Diplomados Data Science en Chile

```{r courses, echo=FALSE}
library(readr)
library(knitr)
data <- read.csv("data.csv")
kable(data)
```

## ¿Cómo añadir un curso/diplomado/magíster a este repositorio?

Fácil, se edita el archivo CSV y se envía una pull request.

## Algunas analíticas

```{r analytics, echo=FALSE, dpi=300, fig.height=6, fig.width=18}
library(ggplot2)
library(gridExtra)
library(ggpubr)

theme_set(theme_pubr())

freqtable1 <- table(data$university)
df1 <- as.data.frame.table(freqtable1)

g1 <- ggplot(df1, aes(Var1, Freq))
g1 <- g1 + geom_bar(stat="identity", width = 0.5, fill="black") + 
  labs(title="Universidades", 
       subtitle="Frecuencia de cursos relacionados con data science",
       x="",
       y="Frecuencia")

freqtable2 <- table(data$category)
df2 <- as.data.frame.table(freqtable2)

g2 <- ggplot(df2, aes(Var1, Freq))
g2 <- g2 + geom_bar(stat="identity", width = 0.5, fill="grey") + 
  labs(title="Categorías", 
       subtitle="Frecuencia de categorías de cursos",
       x="",
       y="Frecuencia")

grid.arrange(g1,g2, ncol=2)

```